### ISSUE TITLE
net/ipx.h: No such file or directory

### ISSUE THREAD

**Issue by Peterdes** [Mange/rtl8192eu-linux-driver#261]
Remove IPX support from driver, set as obsolete in Jan 2018.
IPX is not supported by the Linux kernel since v5.15-rc1, see commit 6c9b40844751ea30c72f7a2f92f4d704bc6b2927

Trying to compile with 5.15.12 kernel yields the error:
`/var/lib/dkms/rtl8192eu/1.0/build/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory`

**Comment by Peterdes** [comment]
I guess something like that should work:
https://github.com/aircrack-ng/rtl8188eus/pull/146/commits/4830d3906230a4d80ba67709a06c9d5b99764839

**Comment by CGarces** [comment]
Hi.
Compilation works fine on 5.15 since Octobrer 2021
https://github.com/Mange/rtl8192eu-linux-driver/runs/3988904696?check_suite_focus=true
See #244 

Are you using a custom kernel from CentOS?

**Comment by Peterdes** [comment]
Oh my. I just I haven't updated the code to the latest version... sorry for the fuss.
