### ISSUE TITLE
DKMS update fails with newer kernel on Manjaro

### ISSUE THREAD

**Issue by noraj** [Mange/rtl8192eu-linux-driver#134]
During a Manjaro upgrade:

```
$ sudo pacman -Syu
[...]
==> dkms install rtl8192eu/1.0 -k 5.1.18-1-MANJARO                                                                                                                                                                                            
Error! Bad return status for module build on kernel: 5.1.18-1-MANJARO (x86_64)                                                                                                                                                                
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.                                                                                                                                                                      
==> dkms install rtl8192eu/1.0 -k 4.19.59-1-MANJARO                                                                                                                                                                                           
Error! Bad return status for module build on kernel: 4.19.59-1-MANJARO (x86_64)                                                                                                                                                               
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.
[...]
```

Advanced logs:

```
$ cat /var/lib/dkms/rtl8192eu/1.0/build/make.log
DKMS make.log for rtl8192eu-1.0 for kernel 4.19.59-1-MANJARO (x86_64)
ven. juil. 19 00:16:38 CEST 2019
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.19.59-1-MANJARO/build M=/var/lib/dkms/rtl8192eu/1.0/build  modules
make[1]: Entering directory '/usr/lib/modules/4.19.59-1-MANJARO/build'
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h: In function ‘_init_timer’:
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:253:8: error: ‘_timer’ {aka ‘struct timer_list’} has no member named ‘data’
  253 |  ptimer->data = (unsigned long)cntx;
      |        ^~
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:254:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  254 |  init_timer(ptimer);
      |  ^~~~~~~~~~
      |  _init_timer
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:304: /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1517: _module_/var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.19.59-1-MANJARO/build'
make: *** [Makefile:1335: modules] Error 2
```

**Comment by CGarces** [comment]
Make sure that you are using branch `realtek-4.4.x`
 The patchs for kernel 4.19.x was done at #98
