### ISSUE TITLE
Support for kernel 4.15?

### ISSUE THREAD

**Issue by tharbad08** [Mange/rtl8192eu-linux-driver#76]
Got this error:

`make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.15.3-2-ARCH/build M=/var/lib/dkms/rtl8192eu/1.0/build  modules
make[1]: Entering directory '/usr/lib/modules/4.15.3-2-ARCH/build'
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45:0,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h: In function ‘_init_timer’:
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:273:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:274:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:317: /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1508: _module_/var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.15.3-2-ARCH/build'
make: *** [Makefile:1700: modules] Error 2
`

I'm guessing it's due to lack of support.

**Comment by MilhouseVH** [comment]
4.15 support added in #70 and confirmed working. I personally built this for x86_64 and arm up to 4.15.0, but haven't tried with anything more recent, so possible that something changed - again - between 4.15.1 and 4.15.3. Or there's an issue with your build host.

**Comment by CGarces** [comment]
Something is wrong on your environment or your are using an incorrect branch.

Branch `realtek-4.4.x `compiles fine on 4.15.4 you can see a full build log [there](https://travis-ci.org/CGarces/rtl8192eu-linux-driver/jobs/343152549).
