### ISSUE TITLE
not working on RHEL 9.1 (Rocky linux )

### ISSUE THREAD

**Issue by enzonun** [Mange/rtl8192eu-linux-driver#309]
make.log file : 

Thu Feb  9 10:34:03 -03 2023
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.14.0-162.12.1.el9_1.0.2.x86_64+debug/build M=/var/lib/dkms/rtl8192eu/1.0/build  modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-162.12.1.el9_1.0.2.x86_64+debug'
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:222:20: error: redefinition of ‘eth_hw_addr_set’
  222 | static inline void eth_hw_addr_set(struct net_device *dev, const u8 *addr)
      |                    ^~~~~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service_linux.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/osdep_service.h:45,
                 from /var/lib/dkms/rtl8192eu/1.0/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.c:17:
./include/linux/etherdevice.h:314:20: note: previous definition of ‘eth_hw_addr_set’ with type ‘void(struct net_device *, const u8 *)’ {aka ‘void(struct net_device *, const unsigned char *)’}
  314 | static inline void eth_hw_addr_set(struct net_device *dev, const u8 *addr)
      |                    ^~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:295: /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1915: /var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-162.12.1.el9_1.0.2.x86_64+debug'
make: *** [Makefile:2287: modules] Error 2

**Comment by fnatter** [comment]
I have the same issue on Debian 11.7. Any updates on this?

Many Thanks,
Felix

**Comment by fnatter** [comment]
did you try 
sudo modprobe rtl8xxxu
This worked fine for me on Debian12 :-)
