### ISSUE TITLE
Cannot build on Linux debian 4.12.1-kirkwood-tld-1 #1 PREEMPT Sat Jul 15 21:40:50 PDT 2017 armv5tel GNU/Linux

### ISSUE THREAD

**Issue by Lalarian** [Mange/rtl8192eu-linux-driver#100]
Hello!

I have been trying to build this driver for 3 months now. But I could not make it work.
The problems already start with the script not finding "sys/socket.h".
So I linked socket.h:
`ln -s /usr/src/linux-headers-4.12.1-kirkwood-tld-1/include/linux/sys/ /usr/src/rtl8192eu-1.0/include/sys
`
But after this the build is stuck at:

root@debian:~/rtl8192eu-linux-driver# make
make ARCH=armv5tel CROSS_COMPILE= -C /lib/modules/4.12.1-kirkwood-tld-1/build M=/root/rtl8192eu-linux-driver  modules
make[1]: Entering directory '/usr/src/linux-headers-4.12.1-kirkwood-tld-1'
  CC [M]  /root/rtl8192eu-linux-driver/core/rtw_cmd.o
In file included from ./include/linux/srcu.h:33:0,
                 from ./include/linux/notifier.h:15,
                 from ./include/linux/memory_hotplug.h:6,
                 from ./include/linux/mmzone.h:758,
                 from ./include/linux/gfp.h:5,
                 from ./include/linux/kmod.h:22,
                 from ./include/linux/module.h:13,
                 from /root/rtl8192eu-linux-driver/include/basic_types.h:81,
                 from /root/rtl8192eu-linux-driver/include/drv_types.h:31,
                 from /root/rtl8192eu-linux-driver/core/rtw_cmd.c:22:
./include/linux/netfilter.h: In function 'nf_hook':
./include/linux/netfilter.h:205:33: error: dereferencing pointer to incomplete type 'struct net'
  hook_head = rcu_dereference(net->nf.hooks[pf][hook]);
                                 ^
./include/linux/rcupdate.h:580:10: note: in definition of macro '__rcu_dereference_check'
  typeof(*p) *________p1 = (typeof(*p) *__force)lockless_dereference(p); \
          ^
./include/linux/rcupdate.h:760:28: note: in expansion of macro 'rcu_dereference_check'
 #define rcu_dereference(p) rcu_dereference_check(p, 0)
                            ^~~~~~~~~~~~~~~~~~~~~
./include/linux/netfilter.h:205:14: note: in expansion of macro 'rcu_dereference'
  hook_head = rcu_dereference(net->nf.hooks[pf][hook]);
              ^~~~~~~~~~~~~~~
scripts/Makefile.build:302: recipe for target '/root/rtl8192eu-linux-driver/core/rtw_cmd.o' failed
make[2]: *** [/root/rtl8192eu-linux-driver/core/rtw_cmd.o] Error 1
Makefile:1512: recipe for target '_module_/root/rtl8192eu-linux-driver' failed
make[1]: *** [_module_/root/rtl8192eu-linux-driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.12.1-kirkwood-tld-1'
Makefile:1700: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by CGarces** [comment]
Hi.

The driver must compile fine on Kernel 4.12

You can test it by yourself in a clean environment modifying the Travic CI script at https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/.travis.yml#L63 , (you must create a fork and activate Travis CI integration).

Please check [this post](https://forum.odroid.com/viewtopic.php?f=95&t=29616) with a similar error
