### ISSUE TITLE
dkms build fails (rocky 9.5, linux 5.14.0)

### ISSUE THREAD

**Issue by heidricha** [Mange/rtl8192eu-linux-driver#347]
Rocky Linux release 9.5 (Blue Onyx)

I tried branches 'master' and '4.4.x'

dkms build fails:

```
[hattila@sv2 rtl8192eu-linux-driver]$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 413c:301a Dell Computer Corp. Dell MS116 Optical Mouse
Bus 001 Device 004: ID 413c:2113 Dell Computer Corp. KB216 Wired Keyboard
Bus 001 Device 007: ID 047f:c058 Plantronics, Inc. Plantronics Blackwire 3225 Series
Bus 001 Device 009: ID 2c4e:0100 Mercucys INC MW300UM RTL8192EU wifi
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
[hattila@sv2 rtl8192eu-linux-driver]$ cat /etc/redhat-release 
Rocky Linux release 9.5 (Blue Onyx)
[hattila@sv2 rtl8192eu-linux-driver]$ sudo dkms remove rtl8192eu/1.0
Module rtl8192eu/1.0 is not installed for kernel 5.14.0-503.19.1.el9_5.x86_64 (x86_64). Skipping...
Module rtl8192eu/1.0 is not built for kernel 5.14.0-503.19.1.el9_5.x86_64 (x86_64). Skipping...

Deleting module rtl8192eu/1.0 completely from the DKMS tree.
[hattila@sv2 rtl8192eu-linux-driver]$ sudo dkms add .
Creating symlink /var/lib/dkms/rtl8192eu/1.0/source -> /usr/src/rtl8192eu-1.0
[hattila@sv2 rtl8192eu-linux-driver]$ sudo dkms build rtl8192eu/1.0

Sign command: /lib/modules/5.14.0-503.19.1.el9_5.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Cleaning build area... done.
Building module(s)..............(bad exit status: 2)
Failed command:
'make' all KVER=5.14.0-503.19.1.el9_5.x86_64

Error! Bad return status for module build on kernel: 5.14.0-503.19.1.el9_5.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8192eu/1.0/build/make.log for more information.
```

error from the compiler:
```
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/rtw_rm_fsm.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/core/efuse/rtw_efuse.o
  CC [M]  /var/lib/dkms/rtl8192eu/1.0/build/os_dep/osdep_service.o
/var/lib/dkms/rtl8192eu/1.0/build/os_dep/osdep_service.c: In function ‘thread_exit’:
/var/lib/dkms/rtl8192eu/1.0/build/os_dep/osdep_service.c:878:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
  878 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:249: /var/lib/dkms/rtl8192eu/1.0/build/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1944: /var/lib/dkms/rtl8192eu/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-503.19.1.el9_5.x86_64'
make: *** [Makefile:2287: modules] Error 2
```
